server:
  port: 8270

spring:
  application:
    name: service-discovery

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${SERVICE_DISCOVERY_URL:http://${eureka:instance:hostname}:${server:port}/eureka/}
  server:
    waitTimeInMsWhenSyncEmpty: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"